import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ReduxProvider } from "@/lib/providers/ReduxProvider";
import { Toaster } from "@/components/ui/sonner"

import "./globals.css";
import AuthInitializer from "@/components/AuthInitializer/AuthInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          <AuthInitializer />
          <TooltipProvider>
              <Toaster />
              {children}
          </TooltipProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
